name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
  workflow_call:

jobs:

  e2e:
    uses: './.github/workflows/e2e.yaml'

  build:
      name: Build and Test
      timeout-minutes: 15
      runs-on: ubuntu-latest
      # To use Remote Caching, uncomment the next lines and follow the steps below.
      # env:
      #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      #  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      #  TURBO_REMOTE_ONLY: true

      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 2

        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 19

        - uses: pnpm/action-setup@v2
          with:
            version: ^8.4
            run_install: |
              - recursive: true
                args: [--frozen-lockfile, --strict-peer-dependencies]

        - name: Lint
          run: pnpm run lint

        - name: Build
          run: pnpm run build

        - name: Test
          run: pnpm run test:ci
