name: E2E Tests

on:
  workflow_call:

jobs:
  playwright:
      name: Playwright tests
      timeout-minutes: 15
      runs-on: ubuntu-latest
      # To use Remote Caching, uncomment the next lines and follow the steps below.
      # env:
      #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      #  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      #  TURBO_REMOTE_ONLY: true

      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 2

        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 19

        - uses: pnpm/action-setup@v2
          with:
            version: ^8.4
            run_install: |
              - recursive: true
                args: [--frozen-lockfile, --strict-peer-dependencies]

        - name: "Install playwright"
          run: pnpm dlx playwright install

        - name: "Run application and playwright"
          run: |
            npm run dev &
            echo "Sleep for 20 sec."
            sleep 20                # Sleep for 20 secs. to give nuxt some time to boot
            echo "Done sleeping"
            npm run test:e2e
